name: Publish PowerShell Module

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Build Module
        shell: pwsh
        run: ./Build.ps1 -Configuration Release

      - name: Run tests
        shell: pwsh
        run: |
          Import-Module ./Module/PSFavorite.psd1 -Force
          Invoke-Pester -Path ./Module/Tests -Output Detailed -PassThru

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --generate-notes

      # TODO: Enable this when ready to publish to PowerShell Gallery
      # - name: Publish to PowerShell Gallery
      #   env:
      #     NUGET_KEY: ${{ secrets.NUGET_KEY }}
      #   shell: pwsh
      #   run: |
      #     Publish-Module -Path "./Module" -NuGetApiKey $env:NUGET_KEY -Verbose
