name: Test

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
    test:
        name: Pester test
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
        
            - name: Run tests
              shell: pwsh
              run: Invoke-Pester -Output Detailed -PassThru
